### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by xiaozixun** [kamo2020/eh-view-enhance#1]
会让所有的图都挤在一起，比如这样：
![捕获](https://user-images.githubusercontent.com/22409452/85914249-431b5700-b86e-11ea-84b8-c7fa73a1935a.PNG)
而我的设置是：
![捕获2](https://user-images.githubusercontent.com/22409452/85914284-a0afa380-b86e-11ea-8b85-56000abdb247.PNG)

**Comment by kamo2020** [comment]
更新一下试试，我昨天更新了一下，适配了chrome，调整了一下样式。
如果还不行，把画廊的地址提供一下

**Comment by xiaozixun** [comment]
> 更新一下试试，我昨天更新了一下，适配了chrome，调整了一下样式。
> 如果还不行，把画廊的地址提供一下

暂时没有问题了，可能是更新时版本号没有变化，所以tampermonkey没有更新。
我还发现个小问题：设置选项有时会被遮掩，尤其是在放大字体后。

**Comment by kamo2020** [comment]
选项被遮掩，现在在选项栏两边有两个箭头，点击箭头可以展开被遮掩的选项。如果不是这样的话，希望能提供截图。
最佳质量图片， 是获取最原始的图片，有时候原图太大了获取失败，有时候连接中断了，获取失败以后图片会有个红框。

**Comment by xiaozixun** [comment]
> 选项被遮掩，现在在选项栏两边有两个箭头，点击箭头可以展开被遮掩的选项。如果不是这样的话，希望能提供截图。
> 最佳质量图片， 是获取最原始的图片，有时候原图太大了获取失败，有时候连接中断了，获取失败以后图片会有个红框。

选项是我的脚本冲突了挡住了，现在好了。
图片质量这个问题有什么办法能解决吗？
