### ISSUE TITLE
exhentai只能加载部分图片

### ISSUE THREAD

**Issue by lilithttf** [kamo2020/eh-view-enhance#13]
现在exhentai的url地址是
```
<a href="https://exhentai.org/s/4e858feec4/2102016-3"><img alt="03" title="Page 3: 002.jpg" src="https://exhentai.org/img/blank.gif" style="width:100px; height:141px; margin:-1px 0 0 -1px" /><br />03</a>
```
extractImageList函数中的正则匹配不上
```
const regx = /(?<=<a\shref=\"(.*?)\">)<img\salt=\"(\d+)\"\stitle=\"(.*?)\"\ssrc=\"(.*?)\".*?><\/a>/g;
```
将它改成就可以了
```
const regx = /(?<=<a\shref=\"(.*?)\">)<img\salt=\"(\d+)\"\stitle=\"(.*?)\"\ssrc=\"(.*?)\".*?<\/a>/g;
```

**Comment by kamo2020** [comment]
画廊中的缩略图需要设置为 Large，这个选项需要登录才可以，检查登录的状态，然后在画廊里点击 Large，切换为更清晰的缩略图模式。
![image](https://user-images.githubusercontent.com/33853879/158338585-34b18b84-bb8d-4a2d-9164-167153d4e2fe.png)
Normal模式采用的CSS切图来展示缩略图图片，质量比较低，就没支持这种模式，这种模式下使用本脚本，点击展开后是没有缩略图的。但是大图依旧有效。

**Comment by kamo2020** [comment]
只能加载部分图片也可能是另一个BUG导致的，滚动时会渲染计算要渲染的空白图片，之前的计算方式有问题，现已修复

**Comment by lilithttf** [comment]
> 画廊中的缩略图需要设置为 Large，这个选项需要登录才可以，检查登录的状态，然后在画廊里点击 Large，切换为更清晰的缩略图模式。 ![image](https://user-images.githubusercontent.com/33853879/158338585-34b18b84-bb8d-4a2d-9164-167153d4e2fe.png) Normal模式采用的CSS切图来展示缩略图图片，质量比较低，就没支持这种模式，这种模式下使用本脚本，点击展开后是没有缩略图的。但是大图依旧有效。

🆗 thanks
