### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by april486** [kamo2020/eh-view-enhance#4]
用这个是只能看缩略图吗，有没有办法提高画质当成正常漫画来看呢。因为用这个加载速度快，但图片实在太糊了

**Comment by kamo2020** [comment]
可以的，一开始是缩略图，然后会自动从第一张开始加载高清图，或者点击某张图也会自动加载这张图的高清图
你用的是什么浏览器，
在使用的时候按一下f12，看看控制台里面有报什么错误信息吗，截图让我看看

**Comment by april486** [comment]
> 可以的，一开始是缩略图，然后会自动从第一张开始加载高清图，或者点击某张图也会自动加载这张图的高清图
> 你用的是什么浏览器，
> 在使用的时候按一下f12，看看控制台里面有报什么错误信息吗，截图让我看看

![image](https://user-images.githubusercontent.com/69881272/91691362-164f2d00-eb9a-11ea-87f5-6ae4f3a9c374.png)
谷歌浏览器，一直是模糊的

**Comment by Pezeo** [comment]
遇到了相同的问题 以下是控制台输出
![Snipaste_2022-10-24_22-24-33](https://user-images.githubusercontent.com/36199396/197632583-6b269abb-3514-4071-a76c-2553f8fdc187.png)

`GalleryMetaoriginTitle: "(C77) [UGC (ささきあきら)] 七咲頼みがあるんだ! (アマガミ)[中国翻訳]"tag: {language:: Array(2), parody:: Array(1), character:: Array(1), group:: Array(1), artist:: Array(1), …}title: "(C77) [UGC (Sasaki Akira)] Nanasaki Tanomi ga Arunda! (Amagami) [Chinese] [甜族星人x我不看本子个人汉化]"url: "https://e-hentai.org/g/2319074/f98f317dbb/"[[Prototype]]: Object
userscript.html?name=P%25E7%25AB%2599%25E5%2588%25A9%25E5%2599%25A8.user.js&id=27142ae6-5d4e-4dc9-9dc3-63bf834f3711:2 
        
       @require: couldn't load @require from URL 'https://storage.googleapis.com/safeweb/jquery.min.js': internal error
tms_27142ae6_5d4e_4dc9_9dc3_63bf834f3711$ @ userscript.html?name=P%25E7%25AB%2599%25E5%2588%25A9%25E5%2599%25A8.user.js&id=27142ae6-5d4e-4dc9-9dc3-63bf834f3711:2
userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:114 
        
       Uncaught (in promise) ReferenceError: $__imu_get_bigimage is not defined
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:114:302313
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:114:302824
    at Proxy.tms_9e2b1c53_340a_4514_88c7_98902006f249$ (userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:114:461670)
    at it (<anonymous>:14:1074)
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:1:124
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:1:777
    at window.__p__6403061.229126936 (userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:115:6)
    at it (<anonymous>:14:1074)
    at set (<anonymous>:3:400)
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:1:34
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1586 2022/10/24 22:21:12 EHVP:所有页码地址加载完毕: Array(1)
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:232 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1586 2022/10/24 22:21:12 EHVP:平均高度为:530
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1586 2022/10/24 22:21:12 EHVP:要渲染的范围是:1- 11
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1586 2022/10/24 22:21:12 EHVP:空闲自加载启动:0
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:266 
        
       Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object.onload (userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:266:67)
    at it (<anonymous>:14:1074)
    at s.onload (<anonymous>:51:4)
    at it (<anonymous>:14:1074)
    at <anonymous>:18:278
    at it (<anonymous>:14:1074)
    at a (<anonymous>:3:446)
    at <anonymous>:4:111
    at <anonymous>:6:169
    at M (<anonymous>:6:188)`

**Comment by kamo2020** [comment]
@Pezeo 更新一下，再看看控制台信息。
由于我无法复现你的问题，现在只是增加了一段异常信息的输出，想要看看在获取大图页面的时候，到底获取到了什么内容。

另外，我看到你提供的信息里有使用其他脚本 P站利器和Image Max Url，我也装了这两个脚本来测试是否是脚本冲突，但并没有测试出问题。

有区别的是，你提供的信息里，P站利器所依赖的另一个脚本因为网络问题未加载出来，并造成了错误。
理论上这个错误对`E-HENTAI-VIEW-ENHANCE`没有什么影响，能影响本脚本的可能还是网络问题。

因此需要你更新`E-HENTAI-VIEW-ENHANCE`后，再尝试一下，并将控制台的输出信息反馈过来。
在控制台的输出信息中，只需要关注  `抽取最佳质量图片地址失败，内容为` 这样的信息就行了

**Comment by Pezeo** [comment]
@kamo2020 
先附上我ehentai设置页面的信息
![QQ图片20221025113215](https://user-images.githubusercontent.com/36199396/197751152-2bcf397a-4ab3-415b-96f5-e1efae936334.png)
更新后的版本号是2.2.2吗？ 问题依旧 没有异常信息的输出 
且发现开启脚本后浏览器右侧页面滚动条消失了（2.2.1版本也有同样的问题） 以下是控制台输出

Uncaught (in promise) ReferenceError: $__imu_get_bigimage is not defined
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:114:302313
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:114:302824
    at Proxy.tms_9e2b1c53_340a_4514_88c7_98902006f249$ (userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:114:461670)
    at it (<anonymous>:14:1074)
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:1:124
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:1:777
    at window.__p__18970633.84956182 (userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:115:6)
    at it (<anonymous>:14:1074)
    at set (<anonymous>:3:400)
    at userscript.html?name=Image%2520Max%2520URL.user.js&id=9e2b1c53-340a-4514-88c7-98902006f249:1:34
content.js:1 hello world content todo something~
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1591 2022/10/25 11:28:03 EHVP:所有页码地址加载完毕: Array(1)
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1591 2022/10/25 11:28:03 EHVP:终止空闲自加载, 下次将从第1张开始加载
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:375 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'setNow')
    at IMGFetcherQueue.do (userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:375:26)
    at stepImageEvent (userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1029:9)
    at HTMLDivElement.bigImageWheelEvent (userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:941:5)
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:232 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1591 2022/10/25 11:28:03 EHVP:平均高度为:530
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1591 2022/10/25 11:28:03 EHVP:要渲染的范围是:1- 11
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1591 2022/10/25 11:28:03 EHVP:空闲自加载启动:0
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:267 
        
       Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object.onload (userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:267:67)
    at it (<anonymous>:14:1074)
    at s.onload (<anonymous>:51:4)
    at it (<anonymous>:14:1074)
    at <anonymous>:18:278
    at it (<anonymous>:14:1074)
    at a (<anonymous>:3:446)
    at <anonymous>:4:111
    at <anonymous>:6:169
    at M (<anonymous>:6:188)
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1591 2022/10/25 11:28:04 EHVP:终止空闲自加载, 下次将从第1张开始加载
3userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:267 
        
       Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object.onload (userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:267:67)
    at it (<anonymous>:14:1074)
    at s.onload (<anonymous>:51:4)
    at it (<anonymous>:14:1074)
    at <anonymous>:18:278
    at it (<anonymous>:14:1074)
    at a (<anonymous>:3:446)
    at <anonymous>:4:111
    at <anonymous>:6:169
    at M (<anonymous>:6:188)
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:1591 2022/10/25 11:28:13 EHVP:空闲自加载启动:6
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:267 
        
       Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object.onload (userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=ee5d8237-6a1c-4d89-8d55-361afa041f4c:267:67)
    at it (<anonymous>:14:1074)
    at s.onload (<anonymous>:51:4)
    at it (<anonymous>:14:1074)
    at <anonymous>:18:278
    at it (<anonymous>:14:1074)
    at a (<anonymous>:3:446)
    at <anonymous>:4:111
    at <anonymous>:6:169
    at M (<anonymous>:6:188)

**Comment by kamo2020** [comment]
是多页查看器的问题，因为多页查看器改变了每张图片预期的页面内容，导致脚本失效了。（因为穷，从来没考虑过多页查看器的情况，这次为了开多页查看器，把我的Credit换的差不多了。。）
我明天就开始修复这个问题，来兼容多页查看器。
你也可以暂时把多页查看器关掉来使用本脚本。

**Comment by Pezeo** [comment]
@kamo2020 关闭多页查看器后脚本工作正常了 不过浏览器滚动条还是会消失
我credit多得没地方用 可以把账号发出来我寄给你一些

**Comment by kamo2020** [comment]
@Pezeo 滚动条的问题，之前特意隐藏页面局部的滚动条，但是没想到把浏览器的也隐藏了，这个问题也会尽快修复。
最近会对这个脚本进行大的升级。

**Comment by kamo2020** [comment]
#

**Comment by kamo2020** [comment]
e4310320fd26619a0fc1892f2eab28977a9cc336
