### ISSUE TITLE
这个插件用了会被锁图片分辨率

### ISSUE THREAD

**Issue by marjax** [kamo2020/eh-view-enhance#7]
![QQ图片20201225091253](https://user-images.githubusercontent.com/18245939/103112587-701bbb80-4691-11eb-80e0-9fd85a81b1d4.png)
只要用了插件看过图，就会被强制锁死在1280x。
而且是锁IP不是锁账号，也就是说用过这个插件后，那个代理节点就永远锁1280x分辨率了。只能切换节点才能更改分辨率。

本来装这个插件是觉得看缩略图又大又方便的，但是锁分辨率那可太伤了，不敢用了，代理节点用一个阵亡一个。

**Comment by marjax** [comment]
看来天菠拉对这类插件的限制还是挺严格的。

**Comment by kamo2020** [comment]
这个没什么办法，尝试了非爬图的方式，也依旧被限制到1280x，不过经过我测试锁分辨率不是永久的，过一段时间就又可以设置到更高的分辨率了。
想看最高质量的图可以在配置里把最佳质量钩上，不过会消耗很多配额。
