### ISSUE TITLE
希望图片默认样式改为"object-fit: contain"，提升竖长窗口体验

### ISSUE THREAD

**Issue by 0z8lkjFHPr** [kamo2020/eh-view-enhance#8]
现在默认样式一律是height: 100%，竖屏观看的话，会超出屏幕右侧。每次都要重新缩放，比较麻烦。如果能改成的话contain的模式就会方便很多，谢谢

**Comment by URenko** [comment]
其实我试过，但是加载的那个边框就炸了

**Comment by kamo2020** [comment]
加上了，也去掉大图的边框了。
